kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: ABAC_PDP_ENDPOINT
      value: {{ ABAC_PDP_ENDPOINT }}
    - name: OPENIDCONNECT_ISSO_JWKS
      value: {{ OPENIDCONNECT_ISSO_JWKS }}
    - name: OPENIDCONNECT_ISSO_ISSUER
      value: {{ OPENIDCONNECT_ISSO_ISSUER }}
    - name: STS_ISSUER
      value: {{ STS_ISSUER }}
    - name: STS_JWKS
      value: {{ STS_JWKS }}
    - name: SPRING_DATASOURCE_URL
      value: {{ SPRING_DATASOURCE_URL }}
  image: {{ image }}
  ingresses:
        {{#each INGRESSES}}
          - {{this }}
        {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  preStopHookPath: internal/prestop
  prometheus:
    enabled: true
    path: internal/metrics
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 1024Mi
  accessPolicy:
    inbound:
      rules:
        - application: gosys-q2
          namespace: isa
  azure:
    application:
      enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: {{ SAKDS }}
        mountPath: /var/run/secrets/nais.io/sakDS
      - kvPath: {{ LDAP }}
        mountPath: /var/run/secrets/nais.io/ldap
      - kvPath: {{ SRVSAK }}
        mountPath: /var/run/secrets/nais.io/srvsak
