kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: ABAC_PDP_ENDPOINT
      value: {{ ABAC_PDP_ENDPOINT }}
    - name: STS_ISSUER
      value: {{ STS_ISSUER }}
    - name: STS_JWKS
      value: {{ STS_JWKS }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
  image: {{ image }}
  ingresses:
        {{#each INGRESSES}}
          - {{this }}
        {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 60m
  accessPolicy:
    inbound:
      rules:
        {{#each INBOUND}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{cluster}}
        {{/each}}
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  vault:
    enabled: true
    paths:
      - kvPath: {{ SAKDB_CREDS }}
        mountPath: "/var/run/secrets/nais.io/db_creds"
      - kvPath: {{ SAKDB_CONFIG }}
        mountPath: "/var/run/secrets/nais.io/db_config"
      - kvPath: {{ LDAP }}
        mountPath: /var/run/secrets/nais.io/ldap
      - kvPath: {{ SRVSAK }}
        mountPath: /var/run/secrets/nais.io/srvsak
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"