kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  envFrom:
    - secret: {{ SAK_SECRET }}
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=75
              $(JAVA_PROXY_OPTIONS) $(JAVA_TRUSTSTORE_OPTIONS)"
    - name: ABAC_PDP_ENDPOINT
      value: {{ ABAC_PDP_ENDPOINT }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_STS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_STS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_STS_ACCEPTED_AUDIENCE }}
    - name: LDAP_USER_BASEDN
      value: {{ LDAP_USER_BASEDN }}
    - name: LDAP_SERVICEUSER_BASEDN
      value: {{ LDAP_SERVICEUSER_BASEDN }}
    - name: LDAP_DOMAIN
      value: {{ LDAP_DOMAIN }}
    - name: LDAP_BASEDN
      value: {{ LDAP_BASEDN }}
    - name: LDAP_URL
      value: {{ LDAP_URL }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
  image: {{ image }}
  ingresses:
        {{#each INGRESSES}}
          - {{this }}
        {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 60m
  accessPolicy:
    inbound:
      rules:
        {{#each INBOUND}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{cluster}}
        {{/each}}
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"