CREATE TABLE sak (
    id                  NUMBER(10)   NOT NULL,
    aktoerid            VARCHAR2(40),
    orgnr               VARCHAR2(9),
    tema                VARCHAR2(40) NOT NULL,
    applikasjon         VARCHAR2(40) NOT NULL,
    fagsaknr            VARCHAR2(40),
    opprettet_av        VARCHAR2(40) NOT NULL,
    opprettet_tidspunkt TIMESTAMP    NOT NULL,
    ENDRET_KILDE_NAVN	VARCHAR2(128),
    DATO_ENDRET	TIMESTAMP,
    BRUKER_ID	VARCHAR2(40),
    K_BRUKER_ID_T	VARCHAR2(40),
    K_SAK_STATUS	VARCHAR2(40),
    OPPRETTET_KILDE_NAVN	VARCHAR2(128),
    ENDRET_AV	VARCHAR2(40),
    DATO_AVSLUTTET	TIMESTAMP,
    AVSLUTTET_AV	VARCHAR2(40),
    AVSLUTTET_KILDE_NAVN	VARCHAR2(40),
    DATO_KASSERT	TIMESTAMP,
    DATO_AVLEVERT	TIMESTAMP,
    DATO_SAK_OPPRETTET	TIMESTAMP,
    ADMINISTRATIV_ENHET	VARCHAR2(128),
    SAK_ANSVARLIG	VARCHAR2(128),
    MERKNAD_OPPRYDDING	VARCHAR2(40),
    K_KASSASJON_STATUS	VARCHAR2(128),
    AVLEVERING_ID	NUMBER(10),
    K_AVLEVERING_STATUS	VARCHAR2(128),

    CONSTRAINT pk_sak PRIMARY KEY (id)
);

CREATE SEQUENCE seq_sak;
