name: Build and deploy to dev

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    uses: navikt/dok-workflows/.github/workflows/build-and-publish.yaml@main
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
    secrets: inherit

  deploy-dev:
    needs: build
    uses: navikt/dok-workflows/.github/workflows/deploy-dev.yaml@main
    strategy:
      matrix:
        environment: [q1, q2]
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
      NAIS_VARIABLES: nais/${{matrix.environment}}-config.json
    secrets: inherit