name: Build, deploy dev feature

on:
  push:
    branches-ignore:
      - main
      - master
      - addtokensupport

jobs:
  build:
    uses: navikt/dok-workflows/.github/workflows/build-deploy-feature.yml@main
    secrets: inherit
