name: Build and deploy to all dev environments, and create release draft

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    uses: navikt/dok-workflows/.github/workflows/build-and-publish.yaml@main
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
    secrets: inherit

  deploy-to-all-dev-environments:
    needs: build-and-publish
    uses: navikt/dok-workflows/.github/workflows/deploy-to-all-dev-environments.yaml@main
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
    secrets: inherit

  update-release-draft:
    uses: navikt/dok-workflows/.github/workflows/release-drafter.yml@main
    needs: deploy-to-all-dev-environments
    secrets: inherit
